name: Using Actions from Marketplace

run-name: Action

on: push

jobs:
  marketplace_actions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go environment
      uses: actions/setup-go@v5.0.1
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges. Be sure to enclose this option in single quotation marks.
        go-version: 1.22.4
        # Path to the go.mod or go.work file.
        #go-version-file: # optional
        # Set this option to true if you want the action to always check for the latest available version that satisfies the version spec
        check-latest: true
        # Used to specify whether caching is needed. Set to true, if you'd like to enable caching.
        #cache: # optional, default is true
        # Used to specify the path to a dependency file - go.sum
        #cache-dependency-path: # optional
        # Target architecture for Go to use. Examples: x86, x64. Will use system architecture by default.
        # architecture: x86 # optional

    - name: Check go version
      run: go version

    - name: Create a file with some text
      run: |
         sudo mkdir -p /home/ubuntu/artifact
         sudo echo action vs reaction > /home/ubuntu/artifact/action.txt

    - name: Upload the file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact1
        path: /home/ubuntu/artifact/action.txt

    - name: Download the artifact created above into /home/ubuntu
      uses: actions/download-artifact@v4
      with:
        name: artifact1
        path: /home/ubuntu

    - name: Check the downloaded artifact
      run: |
          ls /home/ubuntu
          cat /home/ubuntu/action.txt

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Check npm version
      run: npm --version
